#!/bin/bash -l
#SBATCH --job-name=bn
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2      # number of task per a node (number of CPU-cores per a node) 
#SBATCH --mem-per-cpu=1000m      # memory per a CPU-core 
#SBATCH --time=24:00:00
#SBATCH --mail-type=FAIL
#SBATCH --account=engin1

#module load intel
#module load openmpi
module load Chemistry
module load espresso/6.5

srun -n 2 pw.x -npool 2 < scf.in > scf.out
